name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
     - uses: anmol098/waka-readme-stats@master
       with:
         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
         SHOW_TITLE: true
         BLOCKS: ->
         TIME_RANGE: all_time
         SHOW_TIME: false
         SHOW_COMMIT: true
         SHOW_DAYS_OF_WEEK: true
         SHOW_OS: true
         SHOW_PROJECTS: true
         SHOW_EDITORS: true
         SHOW_MASKED_TIME: false
         SHOW_LOC_CHART: "False" 
         SHOW_PROFILE_VIEWS: "False" 
         SHOW_LANGUAGE_PER_REPO: "False"
         SHOW_TIMEZONE: "False"
         SHOW_UPDATED_DATE: "False"
         SHOW_LINES_OF_CODE: "True"
         LOCALE: "en"

    
