name: Waka Readme

 on:
   workflow_dispatch:
   schedule:
     # Runs at 12am UTC
     - cron: "0 0 * * *"

 jobs:
   update-readme:
     name: WakaReadme DevMetrics
     runs-on: ubuntu-latest
     steps:
       - uses: anmol098/waka-readme-stats@master
         with:
           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
           SHOW_TITLE: true
           BLOCKS: ->
           TIME_RANGE: all_time
           SHOW_TIME: false
           SHOW_COMMIT: true
           SHOW_DAYS_OF_WEEK: true
           SHOW_OS: true
           SHOW_PROJECTS: true
           SHOW_EDITORS: true
           SHOW_MASKED_TIME: false
